import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { toast } from 'sonner';
import { Ic } from '../../icons';
import { getTelegramConfig, saveTelegramFileMeta, getExistingFileNames } from '../../lib/supabase';
import { normalizeSizeText } from '../../utils';

// ── Telegram-safe concurrency ───────────────────────────────────────────────────
const BATCH_SIZE     = 10;   // files per batch
const MAX_CONCURRENT = 3;    // simultaneous XHR uploads within a batch
const INTER_BATCH_MS = 800;  // ms cooldown between batches
const MAX_AUTO_RETRIES = 3;  // auto-retry on 429 before showing manual button

// Real filename guard — placeholders generated by the system are never used for dedup
const isRealFileName = (n) =>
  Boolean(n) && n.trim().length > 0 &&
  !n.startsWith('telegram_') && !n.startsWith('file_') && !n.startsWith('tg_file');

export const UploadModal = ({
  open, close, isDark, onUpload,
  user, files = [], disabled = false, onConfigureTelegram,
}) => {
  const [drag, setDrag]         = useState(false);
  const [progress, setProgress] = useState({});
  const ref = useRef(null);

  // Mutable refs — survive async callbacks and re-renders without stale closures
  const filesMapRef     = useRef({}); // { [id]: File } — kept for retry
  const queueRef        = useRef([]); // ids waiting to upload
  const isProcessingRef = useRef(false);
  const credRef         = useRef(null);         // cached TG credentials
  const namesRef        = useRef(null);         // Set<string> of existing lowercase names

  // Reset both caches whenever the modal closes so next open gets a fresh DB check
  useEffect(() => {
    if (!open) {
      namesRef.current  = null;
      credRef.current   = null;
    }
  }, [open]);

  if (!open) return null;

  // ── State helpers ─────────────────────────────────────────────────────────────

  const patchProgress = (id, patch) =>
    setProgress(prev => ({ ...prev, [id]: { ...prev[id], ...patch } }));

  const removeProgress = (id) => {
    setProgress(prev => { const n = { ...prev }; delete n[id]; return n; });
    delete filesMapRef.current[id];
  };

  // ── Utilities ─────────────────────────────────────────────────────────────────

  const getFileType = (f) => {
    if (f.type.startsWith('image')) return 'image';
    if (f.type.startsWith('video')) return 'video';
    if (f.type.startsWith('audio')) return 'music';
    const ext = f.name.split('.').pop()?.toLowerCase();
    if (ext === 'pdf')                    return 'pdf';
    if (['xls','xlsx'].includes(ext))     return 'excel';
    if (['doc','docx'].includes(ext))     return 'word';
    if (['ppt','pptx'].includes(ext))     return 'ppt';
    return 'doc';
  };

  const formatBytes = (bytes) => {
    if (!bytes) return '?';
    if (bytes < 1024)       return `${bytes} B`;
    if (bytes < 1048576)    return `${(bytes / 1024).toFixed(1)} KB`;
    if (bytes < 1073741824) return `${(bytes / 1048576).toFixed(1)} MB`;
    return `${(bytes / 1073741824).toFixed(2)} GB`;
  };

  const getExtension = (name = '') => {
    const p = name.split('.');
    return p.length > 1 ? p.pop().toLowerCase() : '';
  };

  // ── Toast helpers ─────────────────────────────────────────────────────────────

  const showToast = (type, fileName, message) => {
    const isErr  = type === 'error';
    const isWarn = type === 'warning';
    const isSkip = type === 'skip';
    const accent     = isErr ? '#ef4444' : isWarn ? '#f59e0b' : isSkip ? '#6366f1' : '#10b981';
    const accentBg   = isDark
      ? `rgba(${isErr?'239,68,68':isWarn?'245,158,11':isSkip?'99,102,241':'16,185,129'},.13)`
      : `rgba(${isErr?'239,68,68':isWarn?'245,158,11':isSkip?'99,102,241':'16,185,129'},.08)`;
    const panelBg    = isDark
      ? (isErr?'#1c0a0a':isWarn?'#1c1508':isSkip?'#0d0f1c':'#071810')
      : '#fff';
    const border     = isDark
      ? `rgba(${isErr?'239,68,68':isWarn?'245,158,11':isSkip?'99,102,241':'16,185,129'},.25)`
      : (isErr?'#fecaca':isWarn?'#fde68a':isSkip?'#c7d2fe':'#bbf7d0');
    const titleColor = isDark
      ? (isErr?'#fca5a5':isWarn?'#fcd34d':isSkip?'#a5b4fc':'#6ee7b7')
      : (isErr?'#dc2626':isWarn?'#d97706':isSkip?'#4338ca':'#059669');
    const bodyColor  = isDark
      ? (isErr?'#f87171':isWarn?'#fbbf24':isSkip?'#818cf8':'#34d399')
      : (isErr?'#ef4444':isWarn?'#f59e0b':isSkip?'#6366f1':'#10b981');

    const Icon = isErr
      ? <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>
      : isWarn
        ? <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
        : isSkip
          ? <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
          : <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg>;

    const title = isErr ? 'Upload Failed' : isWarn ? 'Warning' : isSkip ? 'Already Exists' : 'Uploaded!';

    toast.custom(() => (
      <div style={{ display:'flex', alignItems:'flex-start', gap:10, padding:'11px 14px', borderRadius:14, background:panelBg, border:`1px solid ${border}`, boxShadow:`0 8px 32px rgba(0,0,0,.14)`, maxWidth:340, width:'100%' }}>
        <div style={{ width:28, height:28, borderRadius:8, flexShrink:0, display:'flex', alignItems:'center', justifyContent:'center', background:accentBg, color:accent }}>{Icon}</div>
        <div style={{ flex:1, minWidth:0 }}>
          <p style={{ fontWeight:700, fontSize:13, color:titleColor, marginBottom:1 }}>{title}</p>
          {fileName && <p style={{ fontSize:11, fontWeight:600, color:bodyColor, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap', maxWidth:210 }}>{fileName}</p>}
          {message  && <p style={{ fontSize:11, color:isDark?'rgba(255,255,255,.4)':'rgba(0,0,0,.4)', marginTop:3, lineHeight:1.4 }}>{message}</p>}
        </div>
      </div>
    ), { duration: isErr ? 6000 : isSkip ? 4000 : isWarn ? 5000 : 3000 });
  };

  // ── Dedup cache ───────────────────────────────────────────────────────────────
  // Loaded once per modal session. Merges the Supabase storage table names
  // with the in-memory `files` prop so we catch both DB-persisted and
  // locally-loaded files without hitting the DB twice.

  const initNamesCache = async () => {
    const uid = user?.$id || 'guest';

    // 1. Fetch real names from the storage table (single query for all files)
    const dbNames = await getExistingFileNames(uid);

    // 2. Merge with in-memory files (covers files loaded but not yet synced to DB,
    //    or files from the current session's localStorage cache)
    (files || []).forEach(f => {
      if (f.name && isRealFileName(f.name)) {
        dbNames.add(f.name.trim().toLowerCase());
      }
    });

    return dbNames;
  };

  // ── Credentials (cached for the modal session) ────────────────────────────────

  const loadCredentials = async () => {
    if (credRef.current) return credRef.current;
    const uid = user?.$id || 'guest';
    const k   = (s) => `tDrive:${uid}:${s}`;
    let tgToken  = localStorage.getItem(k('tgBotToken'));
    let tgChatId = localStorage.getItem(k('tgChatId'));
    try {
      const cfg = await getTelegramConfig(uid);
      if (cfg) {
        tgToken  = cfg.token    || tgToken;
        tgChatId = cfg.chat_id  || tgChatId;
        if (tgToken)  localStorage.setItem(k('tgBotToken'), tgToken);
        if (tgChatId) localStorage.setItem(k('tgChatId'),   tgChatId);
      }
    } catch {}
    credRef.current = { tgToken, tgChatId };
    return credRef.current;
  };

  // ── Telegram XHR upload ───────────────────────────────────────────────────────

  const uploadToTelegram = (f, id, tgToken, tgChatId, attempt = 0) =>
    new Promise((resolve) => {
      const fd = new FormData();
      fd.append('chat_id', tgChatId);
      fd.append('document', f);
      fd.append('caption', `T-Drive: ${f.name}`);

      const xhr = new XMLHttpRequest();
      xhr.open('POST', `https://api.telegram.org/bot${tgToken}/sendDocument`);

      xhr.upload.onprogress = (e) => {
        if (e.lengthComputable)
          patchProgress(id, { prog: (e.loaded / e.total) * 92 });
      };

      xhr.onload = async () => {
        if (xhr.status === 429) {
          let retryAfter = 5;
          try { retryAfter = JSON.parse(xhr.responseText).parameters?.retry_after ?? 5; } catch {}
          if (attempt < MAX_AUTO_RETRIES) {
            patchProgress(id, { status: 'retrying', retryIn: retryAfter, prog: 0 });
            for (let t = retryAfter; t > 0; t--) {
              await new Promise(r => setTimeout(r, 1000));
              patchProgress(id, { retryIn: t - 1 });
            }
            resolve(await uploadToTelegram(f, id, tgToken, tgChatId, attempt + 1));
            return;
          }
          patchProgress(id, { status: 'failed', error: `Rate-limited after ${MAX_AUTO_RETRIES} retries`, prog: 0 });
          resolve({ ok: false });
          return;
        }

        if (xhr.status >= 200 && xhr.status < 300) {
          try {
            const res     = JSON.parse(xhr.responseText);
            const tgMsgId = res.result.message_id;
            const chatId  = res.result.chat?.id;
            const fileId  =
              res.result.document?.file_id ||
              res.result.photo?.[res.result.photo.length - 1]?.file_id ||
              res.result.video?.file_id ||
              res.result.audio?.file_id;
            let tgUrl = null;
            if (fileId) {
              patchProgress(id, { prog: 96 });
              const pr = await fetch(`https://api.telegram.org/bot${tgToken}/getFile?file_id=${fileId}`);
              const pd = await pr.json();
              if (pd.ok) tgUrl = `https://api.telegram.org/file/bot${tgToken}/${pd.result.file_path}`;
            }
            resolve({ ok: true, tgMsgId, chatId, fileId, tgUrl });
          } catch {
            resolve({ ok: true, tgMsgId: null, chatId: null, fileId: null, tgUrl: null });
          }
          return;
        }

        let errorMsg = 'Unknown error';
        try { errorMsg = JSON.parse(xhr.responseText).description || xhr.responseText; } catch {}
        patchProgress(id, { status: 'failed', error: errorMsg, prog: 0 });
        showToast('error', f.name, errorMsg);
        resolve({ ok: false });
      };

      xhr.onerror = () => {
        patchProgress(id, { status: 'failed', error: 'Network error', prog: 0 });
        showToast('error', f.name, 'Network error — check your connection');
        resolve({ ok: false });
      };

      xhr.send(fd);
    });

  // ── Local fallback ────────────────────────────────────────────────────────────

  const simulateLocal = (f, id) =>
    new Promise((resolve) => {
      let p = 0;
      const iv = setInterval(() => {
        p += Math.random() * 18 + 5;
        if (p >= 92) { clearInterval(iv); patchProgress(id, { prog: 92 }); resolve(); }
        else patchProgress(id, { prog: p });
      }, 140);
    });

  // ── Finalize ──────────────────────────────────────────────────────────────────

  const finalizeUpload = async (f, id, tgUrl, tgMsgId, tgChatIdVal, tgFileId) => {
    let tp = 'doc';
    if (f.type.startsWith('image')) tp = 'image';
    else if (f.type.startsWith('video')) tp = 'video';
    else if (f.type.startsWith('audio')) tp = 'music';

    const url  = tgUrl || URL.createObjectURL(f);
    const isTg = Boolean(tgFileId);
    const meta = tgFileId || `local_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`;

    try {
      await saveTelegramFileMeta({
        messageId: tgMsgId, fileId: meta,
        extension: getExtension(f.name) || tp,
        size: normalizeSizeText(f.size),
        userId: user?.$id || user?.id || 'unknown',
        fileName: f.name,
      });
    } catch (e) { console.error('Metadata save failed:', e); }

    onUpload({
      id: tgMsgId ? `tg_${tgMsgId}` : Date.now(),
      name: f.name, type: tp,
      size: normalizeSizeText(f.size),
      date: new Date().toISOString().split('T')[0],
      url, preview: isTg ? url : null,
      thumb: (tp === 'image' || tp === 'video') && isTg ? url : null,
      source: isTg ? 'telegram' : 'local',
      tgFileId, tgChatId: tgChatIdVal, tgMessageId: tgMsgId,
    });

    showToast('success', f.name, isTg ? 'Backed up to Telegram' : 'Saved locally');
    patchProgress(id, { prog: 100, status: 'done' });
    setTimeout(() => removeProgress(id), 1400);
  };

  // ── Single-file upload orchestrator ──────────────────────────────────────────

  const uploadOneFile = async (id) => {
    const f = filesMapRef.current[id];
    if (!f) return;

    patchProgress(id, { status: 'uploading', prog: 0, error: null });

    const { tgToken, tgChatId } = await loadCredentials();
    const oversized = f.size > 50 * 1024 * 1024;

    if (tgToken && tgChatId && !oversized) {
      const res = await uploadToTelegram(f, id, tgToken, tgChatId);
      if (res.ok) await finalizeUpload(f, id, res.tgUrl, res.tgMsgId, res.chatId, res.fileId);
    } else {
      if (oversized) showToast('warning', f.name, '>50 MB — saved locally (Telegram limit)');
      await simulateLocal(f, id);
      await finalizeUpload(f, id);
    }
  };

  // ── Batch queue processor ─────────────────────────────────────────────────────

  const processQueue = async () => {
    if (isProcessingRef.current) return;
    isProcessingRef.current = true;

    while (queueRef.current.length > 0) {
      const batch   = queueRef.current.splice(0, BATCH_SIZE);
      const pending = [...batch];

      const runWorker = async () => {
        while (pending.length > 0) {
          const id = pending.shift();
          await uploadOneFile(id);
        }
      };

      await Promise.all(Array.from({ length: Math.min(MAX_CONCURRENT, batch.length) }, runWorker));

      if (queueRef.current.length > 0)
        await new Promise(r => setTimeout(r, INTER_BATCH_MS));
    }

    isProcessingRef.current = false;
  };

  // ── Retry ─────────────────────────────────────────────────────────────────────

  const retryFile = (id) => {
    if (!filesMapRef.current[id]) return;
    setProgress(prev => ({
      ...prev,
      [id]: { ...prev[id], status: 'queued', prog: 0, error: null, retryCount: (prev[id]?.retryCount ?? 0) + 1 },
    }));
    queueRef.current.push(id);
    processQueue();
  };

  const retryAllFailed = () => {
    Object.entries(progress)
      .filter(([, v]) => v.status === 'failed')
      .forEach(([id]) => retryFile(id));
  };

  // ── Entry point: handleFiles (dedup-aware) ────────────────────────────────────

  const handleFiles = async (fs) => {
    if (!fs.length) return;

    // Lazy-init the dedup cache once per modal session
    if (!namesRef.current) {
      namesRef.current = await initNamesCache();
    }

    const toUpload = [];
    const skipped  = [];

    for (const f of fs) {
      const key = f.name.trim().toLowerCase();

      if (namesRef.current.has(key)) {
        skipped.push(f);
      } else {
        toUpload.push(f);
        // Immediately register the name so a second drop of the same file
        // within this session is also caught without a DB round-trip
        namesRef.current.add(key);
      }
    }

    // ── Show skipped files in the progress list (auto-dismiss after 3s) ─────────
    if (skipped.length > 0) {
      const skipEntries = skipped.map(f => ({
        id:   `skip_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`,
        name: f.name,
        size: f.size,
        fileType: getFileType(f),
      }));

      setProgress(prev => {
        const next = { ...prev };
        skipEntries.forEach(({ id, name, size, fileType }) => {
          next[id] = { name, size, fileType, prog: 0, status: 'skipped', error: null, retryCount: 0 };
        });
        return next;
      });

      // Summary toast
      if (skipped.length === 1) {
        showToast('skip', skipped[0].name, 'Already in your drive — skipped');
      } else {
        showToast('skip', null, `${skipped.length} files already exist — skipped`);
      }

      // Auto-remove skipped rows after 3.5s
      const skipIds = skipEntries.map(e => e.id);
      setTimeout(() => {
        setProgress(prev => {
          const next = { ...prev };
          skipIds.forEach(id => delete next[id]);
          return next;
        });
      }, 3500);
    }

    if (!toUpload.length) return;

    // ── Queue the new (non-duplicate) files ──────────────────────────────────────
    const ids = toUpload.map((f) => {
      const id = `${Date.now()}_${Math.random().toString(36).slice(2, 9)}`;
      filesMapRef.current[id] = f;
      return id;
    });

    setProgress(prev => {
      const next = { ...prev };
      ids.forEach((id, i) => {
        next[id] = {
          name: toUpload[i].name, size: toUpload[i].size,
          fileType: getFileType(toUpload[i]),
          prog: 0, status: 'queued', error: null, retryCount: 0,
        };
      });
      return next;
    });

    queueRef.current.push(...ids);
    processQueue();
  };

  const drop = (e) => { e.preventDefault(); setDrag(false); handleFiles(Array.from(e.dataTransfer.files)); };
  const pick = (e) => handleFiles(Array.from(e.target.files));

  // ── Derived summary counts ────────────────────────────────────────────────────

  const entries    = Object.entries(progress);
  const uploadingN = entries.filter(([, v]) => v.status === 'uploading').length;
  const retryingN  = entries.filter(([, v]) => v.status === 'retrying').length;
  const queuedN    = entries.filter(([, v]) => v.status === 'queued').length;
  const failedN    = entries.filter(([, v]) => v.status === 'failed').length;
  const skippedN   = entries.filter(([, v]) => v.status === 'skipped').length;
  const activeN    = uploadingN + retryingN;
  const avgProg    = entries.length > 0
    ? entries.reduce((s, [, v]) => s + (v.status === 'done' || v.status === 'skipped' ? 100 : v.prog), 0) / entries.length
    : 0;

  const fileIconMap  = { image: Ic.Image, video: Ic.Video, music: Ic.Music, pdf: Ic.Pdf, excel: Ic.Excel, word: Ic.Word, ppt: Ic.Ppt, doc: Ic.Doc };
  const fileColorMap = {
    image: 'text-purple-500 bg-purple-500/10', video: 'text-blue-500 bg-blue-500/10',
    music: 'text-pink-500 bg-pink-500/10',     pdf:   'text-red-500 bg-red-500/10',
    excel: 'text-green-600 bg-green-500/10',   word:  'text-blue-600 bg-blue-500/10',
    ppt:   'text-orange-500 bg-orange-500/10', doc:   'text-gray-500 bg-gray-500/10',
  };

  // ── Render ────────────────────────────────────────────────────────────────────

  return (
    <motion.div
      initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4"
      onClick={close}
    >
      <motion.div
        initial={{ scale: 0.9, y: 12 }} animate={{ scale: 1, y: 0 }} exit={{ scale: 0.9, y: 12 }}
        transition={{ type: 'spring', stiffness: 340, damping: 28 }}
        onClick={(e) => e.stopPropagation()}
        className={`w-full max-w-lg rounded-3xl overflow-hidden shadow-2xl ${isDark ? 'bg-gray-900 border border-gray-700/80' : 'bg-white border border-gray-100'}`}
      >
        {/* Header */}
        <div className={`flex items-center justify-between px-6 py-4 border-b ${isDark ? 'border-gray-700/60' : 'border-gray-100'}`}>
          <div>
            <h2 className={`text-base font-bold leading-tight ${isDark ? 'text-white' : 'text-gray-800'}`}>Upload Files</h2>
            {entries.length > 0 && (
              <p className={`text-[10px] mt-0.5 font-medium ${isDark ? 'text-gray-500' : 'text-gray-400'}`}>
                Batches of {BATCH_SIZE} · {MAX_CONCURRENT} concurrent · duplicates skipped
              </p>
            )}
          </div>
          <button onClick={close} className={`p-2 rounded-xl transition-colors ${isDark ? 'hover:bg-gray-700 text-gray-400' : 'hover:bg-gray-100 text-gray-500'}`}>
            <Ic.X />
          </button>
        </div>

        <div className="p-5 space-y-4">
          {/* Telegram not configured */}
          {disabled ? (
            <div className={`rounded-2xl border px-5 py-5 text-center ${isDark ? 'bg-amber-500/10 border-amber-500/20' : 'bg-amber-50 border-amber-200'}`}>
              <div className={`w-12 h-12 mx-auto rounded-2xl flex items-center justify-center mb-3 ${isDark ? 'bg-amber-400/20 text-amber-300' : 'bg-amber-100 text-amber-600'}`}>
                <Ic.AlertTriangle />
              </div>
              <h3 className={`text-sm font-bold mb-1.5 ${isDark ? 'text-white' : 'text-gray-800'}`}>Telegram not configured</h3>
              <p className={`text-xs mb-4 leading-relaxed ${isDark ? 'text-amber-100/70' : 'text-gray-500'}`}>
                Connect your Telegram bot in Settings to enable uploads.
              </p>
              <div className="flex items-center justify-center gap-2">
                <button onClick={close} className={`px-4 py-2 rounded-xl text-xs font-bold ${isDark ? 'bg-gray-700 text-white' : 'bg-white text-gray-700 border border-gray-200'}`}>Close</button>
                <button onClick={() => { close(); onConfigureTelegram?.(); }} className="px-4 py-2 rounded-xl text-xs font-bold bg-[#0088cc] text-white">Open Settings</button>
              </div>
            </div>
          ) : (
            /* Drop zone */
            <div
              onDragOver={(e) => { e.preventDefault(); setDrag(true); }}
              onDragLeave={() => setDrag(false)}
              onDrop={drop}
              onClick={() => ref.current?.click()}
              className={`border-2 border-dashed rounded-2xl py-7 text-center cursor-pointer transition-all ${drag ? 'border-emerald-500 bg-emerald-500/10 scale-[1.01]' : isDark ? 'border-gray-600/50 hover:border-emerald-400/40 hover:bg-emerald-500/5' : 'border-gray-200 hover:border-emerald-400 hover:bg-emerald-50/50'}`}
            >
              <motion.div
                animate={drag ? { scale: [1, 1.18, 1] } : { scale: 1 }}
                transition={{ repeat: drag ? Infinity : 0, duration: 0.9 }}
                className={`w-14 h-14 mx-auto rounded-2xl flex items-center justify-center mb-3 ${drag ? 'bg-emerald-500 text-white' : isDark ? 'bg-gray-700/80 text-gray-400' : 'bg-emerald-100 text-emerald-500'}`}
              >
                <Ic.Upload />
              </motion.div>
              <p className={`text-sm font-semibold ${isDark ? 'text-gray-300' : 'text-gray-600'}`}>{drag ? 'Drop files here' : 'Drag & drop files'}</p>
              <p className={`text-[11px] mt-1 ${isDark ? 'text-gray-500' : 'text-gray-400'}`}>
                or click to browse · batches of {BATCH_SIZE} · duplicates auto-skipped
              </p>
              <input ref={ref} type="file" multiple onChange={pick} className="hidden" />
            </div>
          )}

          {/* Upload queue panel */}
          {entries.length > 0 && (
            <div className={`rounded-2xl border overflow-hidden ${isDark ? 'bg-gray-800/60 border-gray-700/60' : 'bg-gray-50/80 border-gray-200/80'}`}>

              {/* Summary row */}
              <div className={`px-4 py-3 border-b ${isDark ? 'border-gray-700/60' : 'border-gray-200/60'}`}>
                <div className="flex items-center justify-between gap-2 mb-2.5">
                  <div className="flex items-center gap-1.5 flex-wrap">
                    {activeN > 0 && (
                      <span className={`inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full ${isDark ? 'bg-emerald-500/15 text-emerald-400' : 'bg-emerald-100 text-emerald-700'}`}>
                        <motion.span animate={{ opacity: [1, 0.25, 1] }} transition={{ repeat: Infinity, duration: 1.1 }}>●</motion.span>
                        {activeN} uploading
                      </span>
                    )}
                    {queuedN > 0 && (
                      <span className={`inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full ${isDark ? 'bg-gray-700 text-gray-400' : 'bg-gray-200 text-gray-600'}`}>
                        ⏳ {queuedN} queued
                      </span>
                    )}
                    {skippedN > 0 && (
                      <span className="inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full bg-indigo-500/15 text-indigo-400">
                        ↷ {skippedN} skipped
                      </span>
                    )}
                    {failedN > 0 && (
                      <span className="inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full bg-red-500/15 text-red-400">
                        ✕ {failedN} failed
                      </span>
                    )}
                  </div>
                  <div className="flex items-center gap-2 flex-shrink-0">
                    {failedN > 1 && (
                      <button
                        onClick={retryAllFailed}
                        className={`text-[10px] font-bold px-2.5 py-1 rounded-lg transition-colors ${isDark ? 'bg-red-500/20 text-red-400 hover:bg-red-500/30' : 'bg-red-50 text-red-600 hover:bg-red-100'}`}
                      >
                        Retry all
                      </button>
                    )}
                    <span className={`text-[11px] font-bold tabular-nums ${isDark ? 'text-emerald-400' : 'text-emerald-600'}`}>
                      {Math.round(avgProg)}%
                    </span>
                  </div>
                </div>

                {/* Overall progress bar */}
                <div className={`h-1.5 rounded-full overflow-hidden ${isDark ? 'bg-gray-700' : 'bg-gray-200'}`}>
                  <motion.div
                    className="h-full rounded-full bg-gradient-to-r from-emerald-500 to-teal-400"
                    animate={{ width: `${avgProg}%` }}
                    transition={{ type: 'spring', stiffness: 50, damping: 14 }}
                  />
                </div>
              </div>

              {/* File list */}
              <div className="upload-scroll overflow-y-auto" style={{ maxHeight: 272 }}>
                <AnimatePresence initial={false}>
                  {entries.map(([id, item]) => {
                    const FileIcon   = fileIconMap[item.fileType] || Ic.Doc;
                    const colorCls   = fileColorMap[item.fileType] || fileColorMap.doc;
                    const isFailed   = item.status === 'failed';
                    const isQueued   = item.status === 'queued';
                    const isRetrying = item.status === 'retrying';
                    const isDone     = item.status === 'done';
                    const isSkipped  = item.status === 'skipped';

                    return (
                      <motion.div
                        key={id}
                        layout
                        initial={{ opacity: 0, y: 6 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, height: 0 }}
                        transition={{ duration: 0.15 }}
                        className={[
                          'px-3 py-2.5 border-b last:border-b-0',
                          isDark ? 'border-gray-700/40' : 'border-gray-200/40',
                          isFailed  ? (isDark ? 'bg-red-500/5'    : 'bg-red-50/60')    : '',
                          isRetrying? (isDark ? 'bg-amber-500/5'  : 'bg-amber-50/60')  : '',
                          isDone    ? (isDark ? 'bg-emerald-500/5': 'bg-emerald-50/30'): '',
                          isSkipped ? (isDark ? 'bg-indigo-500/5' : 'bg-indigo-50/40') : '',
                          isQueued  ? 'opacity-55' : '',
                        ].join(' ')}
                      >
                        <div className="flex items-center gap-2.5">
                          {/* Icon */}
                          <div className={[
                            'w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 text-sm',
                            isDone     ? 'text-emerald-500 bg-emerald-500/10' :
                            isFailed   ? 'text-red-500 bg-red-500/10'         :
                            isRetrying ? 'text-amber-500 bg-amber-500/10'     :
                            isSkipped  ? 'text-indigo-400 bg-indigo-500/10'   :
                            colorCls,
                          ].join(' ')}>
                            {isDone ? <Ic.Check />
                              : isFailed
                                ? <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><line x1="15" y1="9" x2="9" y2="15"/><line x1="9" y1="9" x2="15" y2="15"/></svg>
                              : isRetrying
                                ? <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1, ease: 'linear' }}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/><path d="M3 3v5h5"/></svg></motion.div>
                              : isSkipped
                                ? <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
                              : <FileIcon />
                            }
                          </div>

                          {/* Name + status text */}
                          <div className="flex-1 min-w-0">
                            <p className={`text-xs font-semibold truncate leading-tight ${isDark ? 'text-gray-200' : 'text-gray-700'}`}>{item.name}</p>
                            <div className="flex items-center gap-1.5 mt-0.5 flex-wrap">
                              <span className={`text-[10px] ${isDark ? 'text-gray-500' : 'text-gray-400'}`}>{formatBytes(item.size)}</span>
                              {isSkipped && (
                                <span className="text-[10px] font-semibold text-indigo-400">Already in drive — skipped</span>
                              )}
                              {isRetrying && (
                                <span className="text-[10px] font-semibold text-amber-500">
                                  Rate limited · retrying{item.retryIn > 0 ? ` in ${item.retryIn}s` : '…'}
                                </span>
                              )}
                              {isFailed && item.error && (
                                <span className="text-[10px] text-red-400 truncate max-w-[130px]">{item.error}</span>
                              )}
                              {isQueued && (
                                <span className={`text-[10px] font-medium ${isDark ? 'text-gray-600' : 'text-gray-400'}`}>In queue</span>
                              )}
                            </div>
                          </div>

                          {/* Right: % or Retry or skipped badge */}
                          <div className="flex-shrink-0">
                            {isFailed ? (
                              <button
                                onClick={() => retryFile(id)}
                                className={`flex items-center gap-1 text-[10px] font-bold px-2.5 py-1 rounded-lg transition-all active:scale-95 ${isDark ? 'bg-red-500/20 text-red-400 hover:bg-red-500/30' : 'bg-red-100 text-red-600 hover:bg-red-200'}`}
                              >
                                <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/><path d="M3 3v5h5"/></svg>
                                Retry{item.retryCount > 0 ? ` (${item.retryCount})` : ''}
                              </button>
                            ) : isSkipped ? (
                              <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-indigo-500/15 text-indigo-400">Skipped</span>
                            ) : (
                              <span className={`text-xs font-bold tabular-nums w-9 text-right ${isDone ? 'text-emerald-500' : isRetrying ? 'text-amber-500' : isQueued ? (isDark ? 'text-gray-600' : 'text-gray-400') : (isDark ? 'text-emerald-400' : 'text-emerald-600')}`}>
                                {isQueued ? '—' : `${Math.round(item.prog)}%`}
                              </span>
                            )}
                          </div>
                        </div>

                        {/* Progress bar (only for active / done states) */}
                        {!isQueued && !isFailed && !isSkipped && (
                          <div className={`mt-2 h-1 rounded-full overflow-hidden ${isDark ? 'bg-gray-700' : 'bg-gray-200'}`}>
                            <motion.div
                              className={`h-full rounded-full ${isDone ? 'bg-emerald-500' : isRetrying ? 'bg-amber-400' : 'bg-gradient-to-r from-emerald-500 to-teal-400'}`}
                              animate={{ width: `${isDone ? 100 : item.prog}%` }}
                              transition={{ type: 'spring', stiffness: 55, damping: 14 }}
                            />
                          </div>
                        )}
                      </motion.div>
                    );
                  })}
                </AnimatePresence>
              </div>
            </div>
          )}
        </div>
      </motion.div>
    </motion.div>
  );
};
